### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by OctoNezd** [soulwing/guacamole-auth-rest#2]
Hi! Is there any instruction on installing this extension?
I tried to build the extension with `mvn package`, and put resulting .jar in GUACAMOLE_HOME/extensions, but it fails to load cause it can't find class of one of dependencies. I tried putting dependencies in extensions but it didn't work.

**Comment by ceharris** [comment]
In Guacamole, dependencies for an extension need to go in `GUACAMOLE_HOME/lib`. So you want to put the extension in `extension/` and the dependencies in `lib\`. During the maven build, jar files for the dependencies are copied into `target/dependency/`.

**Comment by ceharris** [comment]
I updated the README to include some very basic installation instructions. Let me know if you still need help getting it working.
